# Generated by Django 4.0.1 on 2022-01-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=60)),
                ('prix', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
